/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BugreportRouteImport } from './routes/bugreport'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServerRouteImport } from './routes/server'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminOperationsRouteImport } from './routes/admin/operations'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as DevEmailOutboxRouteImport } from './routes/dev/email-outbox'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as RankingSlugRouteImport } from './routes/ranking/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BugreportRoute = BugreportRouteImport.update({
  id: '/bugreport',
  path: '/bugreport',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const DevEmailOutboxRoute = DevEmailOutboxRouteImport.update({
  id: '/dev/email-outbox',
  path: '/dev/email-outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const RankingSlugRoute = RankingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RankingRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bugreport': typeof BugreportRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/ranking': typeof RankingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/server': typeof ServerRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/dev/email-outbox': typeof DevEmailOutboxRoute
  '/news/$slug': typeof NewsSlugRoute
  '/ranking/$slug': typeof RankingSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bugreport': typeof BugreportRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/ranking': typeof RankingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/server': typeof ServerRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/dev/email-outbox': typeof DevEmailOutboxRoute
  '/news/$slug': typeof NewsSlugRoute
  '/ranking/$slug': typeof RankingSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bugreport': typeof BugreportRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/ranking': typeof RankingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/server': typeof ServerRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/dev/email-outbox': typeof DevEmailOutboxRoute
  '/news/$slug': typeof NewsSlugRoute
  '/ranking/$slug': typeof RankingSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/bugreport'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/news'
    | '/ranking'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/server'
    | '/verify-email'
    | '/admin/campaigns'
    | '/admin/comments'
    | '/admin/news'
    | '/admin/operations'
    | '/admin/reports'
    | '/dev/email-outbox'
    | '/news/$slug'
    | '/ranking/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/bugreport'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/news'
    | '/ranking'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/server'
    | '/verify-email'
    | '/admin/campaigns'
    | '/admin/comments'
    | '/admin/news'
    | '/admin/operations'
    | '/admin/reports'
    | '/dev/email-outbox'
    | '/news/$slug'
    | '/ranking/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/bugreport'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/news'
    | '/ranking'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/server'
    | '/verify-email'
    | '/admin/campaigns'
    | '/admin/comments'
    | '/admin/news'
    | '/admin/operations'
    | '/admin/reports'
    | '/dev/email-outbox'
    | '/news/$slug'
    | '/ranking/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BugreportRoute: typeof BugreportRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  RankingRoute: typeof RankingRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ServerRoute: typeof ServerRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DevEmailOutboxRoute: typeof DevEmailOutboxRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugreport': {
      id: '/bugreport'
      path: '/bugreport'
      fullPath: '/bugreport'
      preLoaderRoute: typeof BugreportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dev/email-outbox': {
      id: '/dev/email-outbox'
      path: '/dev/email-outbox'
      fullPath: '/dev/email-outbox'
      preLoaderRoute: typeof DevEmailOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/ranking/$slug': {
      id: '/ranking/$slug'
      path: '/$slug'
      fullPath: '/ranking/$slug'
      preLoaderRoute: typeof RankingSlugRouteImport
      parentRoute: typeof RankingRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminReportsRoute: AdminReportsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface RankingRouteChildren {
  RankingSlugRoute: typeof RankingSlugRoute
}

const RankingRouteChildren: RankingRouteChildren = {
  RankingSlugRoute: RankingSlugRoute,
}

const RankingRouteWithChildren =
  RankingRoute._addFileChildren(RankingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BugreportRoute: BugreportRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  RankingRoute: RankingRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ServerRoute: ServerRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DevEmailOutboxRoute: DevEmailOutboxRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
